Chapter 05

# 爱因斯坦求和约定
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

这段代码使用 `numpy` 库的 `einsum` 函数进行各种矩阵和向量的运算。`einsum` 函数的主要优势在于其高效的索引处理方式，使得许多复杂的矩阵和向量操作可以用简单的字符串表达式来实现。这段代码包括以下几个主要部分：

1. **定义向量与矩阵**：  
   定义了两个列向量

   $$ a = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} $$
   $$ b = \begin{bmatrix} -4 \\ -5 \\ -6 \end{bmatrix} $$

   以及它们对应的一维向量形式 \( a_{1D} = [1, 2, 3] \) 和 \( b_{1D} = [-4, -5, -6] \)。

3. **向量和矩阵的求和**：  
   使用 `einsum('ij->', a)` 计算 \( a \) 中所有元素的和，即 \( \sum_{i,j} a_{ij} \)。  
   同样地，`einsum('i->', a_{1D})` 计算 \( a_{1D} \) 的元素和，即 \( \sum_i a_{i} \)。

4. **逐元素乘积**：  
   使用 `einsum('ij,ij->ij', a, b)` 计算 \( a \) 和 \( b \) 的逐元素乘积，其结果为一个矩阵，其中每个元素 \( (i,j) \) 对应 \( a_{ij} \times b_{ij} \)。  
   对一维向量 `a_1D` 和 `b_1D` 的逐元素乘积，则通过 `einsum('i,i->i', a_{1D}, b_{1D})` 实现，得到 \( [a_1 \times b_1, a_2 \times b_2, a_3 \times b_3] \)。

5. **向量的内积**：  
   使用 `einsum('ij,ij->', a, b)` 计算 \( a \) 和 \( b \) 的内积，即 \( \sum_{i,j} a_{ij} \cdot b_{ij} \)。  
   类似地，对于一维向量的内积，通过 `einsum('i,i->', a_{1D}, b_{1D})` 计算，公式为 \( \sum_i a_i \cdot b_i \)。

6. **向量的外积**：  
   `einsum('ij,ji->ij', a, a)` 计算向量 \( a \) 自身的外积，生成一个矩阵，每个元素为 \( a_{ij} \cdot a_{ji} \)。  
   而 `einsum('i,j->ij', a_{1D}, a_{1D})` 计算 \( a_{1D} \) 的外积，得到一个 \( 3 \times 3 \) 矩阵，其元素为 \( a_i \cdot a_j \)。

7. **矩阵的定义及运算**：  
   定义了两个 \( 3 \times 3 \) 的矩阵 \( A \) 和 \( B \)。矩阵 \( A \) 和 \( B \) 之间的运算包括以下内容：  
   
   - **转置**： `einsum('ji', A)` 计算 \( A \) 的转置。
   
   - **矩阵求和**： `einsum('ij->', A)` 计算矩阵 \( A \) 所有元素的和。  
   
   - **按行和按列求和**：  
     使用 `einsum('ij->j', A)` 计算每列的和，结果为一个一维数组，形式为 \( \sum_i A_{ij} \)。  
     `einsum('ij->i', A)` 计算每行的和，结果形式为 \( \sum_j A_{ij} \)。

   - **提取主对角线和计算迹**：  
     `einsum('ii->i', A)` 提取 \( A \) 的主对角线元素，结果为 \( [A_{11}, A_{22}, A_{33}] \)。  
     `einsum('ii->', A)` 计算矩阵 \( A \) 的迹 \( \text{tr}(A) = \sum_i A_{ii} \)。

   - **矩阵乘法和结果求和**：  
     `einsum('ij,jk->ik', A, B)` 计算 \( A \) 和 \( B \) 的矩阵乘积 \( C = A \times B \)，即 \( C_{ik} = \sum_j A_{ij} \cdot B_{jk} \)。  
     `einsum('ij,jk->', A, B)` 计算 \( A \times B \) 的所有元素和。  
     `einsum('ij,jk->ki', A, B)` 先进行矩阵乘法，再对结果转置。

   - **逐元素乘积**：  
     `einsum('ij,ij->ij', A, B)` 计算 \( A \) 和 \( B \) 的逐元素乘积，结果为矩阵 \( D \)，其中 \( D_{ij} = A_{ij} \cdot B_{ij} \)。

In [1]:
import numpy as np

## 定义矩阵和向量

In [2]:
a = np.array([[1],
              [2],
              [3]])  # 定义列向量 a

In [3]:
a_1D = np.array([1,2,3])  # 定义一维向量 a_1D

In [4]:
b = np.array([[-4],
              [-5],
              [-6]])  # 定义列向量 b

In [5]:
b_1D = np.array([-4,-5,-6])  # 定义一维向量 b_1D

## 计算向量 a 的元素和

In [6]:
print(np.einsum('ij->',a))  # 计算矩阵 a 所有元素的和

6


In [7]:
print(np.einsum('i->',a_1D))  # 计算向量 a_1D 所有元素的和

6


## 向量 a 和 b 的逐元素乘积

In [8]:
print(np.einsum('ij,ij->ij',a,b))  # 计算矩阵 a 和 b 的逐元素乘积

[[ -4]
 [-10]
 [-18]]


In [9]:
print(np.einsum('i,i->i',a_1D,b_1D))  # 计算向量 a_1D 和 b_1D 的逐元素乘积

[ -4 -10 -18]


## 向量 a 和 b 的内积

In [10]:
print(np.einsum('ij,ij->',a,b))  # 计算矩阵 a 和 b 的内积

-32


In [11]:
print(np.einsum('i,i->',a_1D,b_1D))  # 计算向量 a_1D 和 b_1D 的内积

-32


## 向量 a 自身的外积

In [12]:
print(np.einsum('ij,ji->ij',a,a))  # 计算矩阵 a 和自身的外积

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [13]:
print(np.einsum('i,j->ij',a_1D,a_1D))  # 计算向量 a_1D 和自身的外积

[[1 2 3]
 [2 4 6]
 [3 6 9]]


## 向量 a 和 b 的外积

In [ ]:
print(np.einsum('ij,ji->ij',a,b))  # 计算矩阵 a 和 b 的外积

In [ ]:
print(np.einsum('i,j->ij',a_1D,b_1D))  # 计算向量 a_1D 和 b_1D 的外积

[[ -4  -5  -6]
 [ -8 -10 -12]
 [-12 -15 -18]]
[[ -4  -5  -6]
 [ -8 -10 -12]
 [-12 -15 -18]]


## 定义方阵 A 和 B

In [15]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])  # 定义方阵 A

In [16]:
B = np.array([[-1,-4,-7],
              [-2,-5,-8],
              [-3,-6,-9]])  # 定义方阵 B

## A 的转置

In [17]:
print(np.einsum('ji',A))  # 计算矩阵 A 的转置

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## A 的元素和

In [18]:
print(np.einsum('ij->',A))  # 计算矩阵 A 所有元素的和

45


## 按行求和

In [19]:
print(np.einsum('ij->j',A))  # 计算矩阵 A 的每列的和

[12 15 18]


## 按列求和

In [20]:
print(np.einsum('ij->i',A))  # 计算矩阵 A 的每行的和

[ 6 15 24]


## 提取主对角线

In [21]:
print(np.einsum('ii->i',A))  # 提取矩阵 A 的主对角线元素

[1 5 9]


## 计算矩阵 A 的迹

In [22]:
print(np.einsum('ii->',A))  # 计算矩阵 A 的迹（主对角线元素的和）

15


## 矩阵 A 和 B 的乘积

In [23]:
print(np.einsum('ij,jk->ik', A, B))  # 计算矩阵 A 和 B 的矩阵乘法

[[ -14  -32  -50]
 [ -32  -77 -122]
 [ -50 -122 -194]]


## A 和 B 的矩阵乘积的所有元素和

In [24]:
print(np.einsum('ij,jk->', A, B))  # 计算矩阵 A 和 B 的乘积矩阵的所有元素的和

-693


## 矩阵相乘后转置

In [25]:
print(np.einsum('ij,jk->ki', A, B))  # 计算矩阵 A 和 B 的乘积后对结果转置

[[ -14  -32  -50]
 [ -32  -77 -122]
 [ -50 -122 -194]]


## A 和 B 的逐元素乘积

In [26]:
print(np.einsum('ij,ij->ij', A, B))  # 计算矩阵 A 和 B 的逐元素乘积

[[ -1  -8 -21]
 [ -8 -25 -48]
 [-21 -48 -81]]
