Chapter 14

# 矩阵平方根
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码的主要任务是通过矩阵分解和重构方法，基于给定的矩阵$A$，验证矩阵重构的正确性。具体流程如下：

1. **定义矩阵$A$**：  
   代码首先创建了一个$2 \times 2$矩阵 $A = \begin{bmatrix} 1.25 & -0.75 \\ -0.75 & 1.25 \end{bmatrix}$。矩阵 $A$ 是一个对称矩阵，因此可以进行特征值分解。

2. **计算特征值和特征向量**：  
   代码使用 `np.linalg.eig` 函数对矩阵 $A$ 进行特征值分解，计算出$A$的特征值（存储在 $LAMBDA$ 中）和特征向量（存储在 $V$ 中），满足以下分解公式：
   $$
   A = V \Lambda V^{-1}
   $$
   其中，$\Lambda$ 是一个包含特征值的对角矩阵，$V$ 是由特征向量组成的矩阵。

3. **构建矩阵$B$**：  
   接下来，代码构建了一个新的矩阵 $B$。它的计算公式为：
   $$
   B = V \sqrt{\Lambda} V^{-1}
   $$
   其中，$\sqrt{\Lambda}$ 是对角矩阵，其对角元素是 $\Lambda$ 的平方根。也就是说，$B$ 是通过将 $A$ 的特征值取平方根后重新组合得到的矩阵。

4. **重构矩阵$A$并验证结果**：  
   最后，通过矩阵 $B$ 构造了一个新矩阵 $A_{reproduced}$，其计算公式为：
   $$
   A_{reproduced} = B B^T
   $$
   这是利用矩阵 $B$ 重构 $A$ 的过程。对称矩阵 $A$ 的特征值平方根分解使得 $B B^T$ 应等于原始矩阵 $A$。因此，通过打印 $A_{reproduced}$，可以验证 $B B^T$ 是否等于 $A$，从而确认重构的正确性。

In [1]:
import numpy as np  # 导入NumPy库

## 初始化矩阵A

In [2]:
A = np.matrix([[1.25, -0.75],  # 定义矩阵A
               [-0.75, 1.25]])  # 矩阵的元素

## 计算特征值和特征向量

In [3]:
LAMBDA, V = np.linalg.eig(A)  # 计算矩阵A的特征值（LAMBDA）和特征向量（V）

In [4]:
LAMBDA

array([2. , 0.5])

In [5]:
V

matrix([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]])

## 构建矩阵B

In [6]:
B = V @ np.diag(np.sqrt(LAMBDA)) @ np.linalg.inv(V)  # 根据特征值和特征向量构建矩阵B

In [7]:
B

matrix([[ 1.06066017, -0.35355339],
        [-0.35355339,  1.06066017]])

## 重构矩阵A并打印

In [8]:
A_reproduced = B @ B.T  # 通过矩阵B的转置乘积重构矩阵A
print(A_reproduced)  # 输出重构后的矩阵A

[[ 1.25 -0.75]
 [-0.75  1.25]]
