Chapter 06

# 分块矩阵
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

这段代码演示了如何对矩阵进行分块和重组操作。首先定义了一个 \(4 \times 5\) 矩阵 \( A \)：

$$
A = \begin{bmatrix}
1 & 2 & 3 & 0 & 0 \\
4 & 5 & 6 & 0 & 0 \\
0 & 0 & 0 & -1 & 0 \\
0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}
$$

然后使用 NumPy 的切片方法，将矩阵 \( A \) 分割为 4 个子矩阵（即 \(2 \times 2\) 的块矩阵结构）：

1. \( A_{1,1} = A[0:2, 0:3] \)，即前两行和前三列的子矩阵：
   $$
   A_{1,1} = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
   $$
   
2. \( A_{1,2} = A[0:2, 3:] \)，即前两行和最后两列的子矩阵：
   $$
   A_{1,2} = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix}
   $$

3. \( A_{2,1} = A[2:, 0:3] \)，即后两行和前三列的子矩阵：
   $$
   A_{2,1} = \begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}
   $$

4. \( A_{2,2} = A[2:, 3:] \)，即后两行和最后两列的子矩阵：
   $$
   A_{2,2} = \begin{bmatrix} -1 & 0 \\ 0 & 1 \end{bmatrix}
   $$

最后使用 `np.block` 函数将这些子矩阵重新组合为一个新的矩阵 \( A' \)，其结构与原矩阵 \( A \) 相同：

$$
A' = \begin{bmatrix} 
A_{1,1} & A_{1,2} \\ 
A_{2,1} & A_{2,2} 
\end{bmatrix} = 
\begin{bmatrix} 
1 & 2 & 3 & 0 & 0 \\ 
4 & 5 & 6 & 0 & 0 \\ 
0 & 0 & 0 & -1 & 0 \\ 
0 & 0 & 0 & 0 & 1 
\end{bmatrix}
$$ 

通过这种方法，可以方便地在分块矩阵操作中对矩阵进行重新组合，实现了矩阵的分解与重构。

In [1]:
import numpy as np

## 定义矩阵 A

In [2]:
A = np.array([[1, 2, 3, 0,  0],   # 定义矩阵 A 的元素
              [4, 5, 6, 0,  0],
              [0, 0, 0, -1, 0],
              [0, 0 ,0, 0,  1]])
A

array([[ 1,  2,  3,  0,  0],
       [ 4,  5,  6,  0,  0],
       [ 0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  1]])

## NumPy 数组切片操作

In [3]:
A_1_1 = A[0:2,0:3]  # 提取矩阵 A 的前两行和前三列作为子矩阵 A_1_1
A_1_1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A_1_2 = A[0:2,3:]  # 提取矩阵 A 的前两行和最后两列作为子矩阵 A_1_2
A_1_2
# A_1_2 = A[0:2,-2:]  # 或者用负索引方式提取前两行和最后两列（注释部分）

array([[0, 0],
       [0, 0]])

In [5]:
A_2_1 = A[2:,0:3]  # 提取矩阵 A 的后两行和前三列作为子矩阵 A_2_1
A_2_1
# A_2_1 = A[-2:,0:3]  # 或者用负索引方式提取后两行和前三列（注释部分）

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
A_2_2 = A[2:,3:]  # 提取矩阵 A 的后两行和最后两列作为子矩阵 A_2_2
A_2_2
# A_2_2 = A[-2:,-2:]  # 或者用负索引方式提取后两行和最后两列（注释部分）

array([[-1,  0],
       [ 0,  1]])

## 使用嵌套列表中的块组装矩阵

In [7]:
A_ = np.block([[A_1_1, A_1_2],   # 通过 np.block 函数将子矩阵 A_1_1、A_1_2、A_2_1 和 A_2_2 组合成新的矩阵 A_
               [A_2_1, A_2_2]])
A_

array([[ 1,  2,  3,  0,  0],
       [ 4,  5,  6,  0,  0],
       [ 0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  1]])