Chapter 04

# 矩阵幂
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码演示了在 NumPy 中如何计算矩阵的三次幂与逐元素三次方的区别：

1. **矩阵的三次幂**：通过 `matrix_power` 或连续的矩阵乘法 `A @ A @ A` 计算矩阵 $A$ 的三次幂。给定矩阵：

   $$
   A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
   $$

   其三次幂 $A^3$ 计算为：

   $$
   A^3 = A @ A @ A = \begin{bmatrix} 37 & 54 \\ 81 & 118 \end{bmatrix}
   $$

2. **逐元素三次方**：`A ** 3` 计算的是矩阵 $A$ 每个元素的三次方，结果为：

   $$
   A \odot A \odot A = \begin{bmatrix} 1^3 & 2^3 \\ 3^3 & 4^3 \end{bmatrix} = \begin{bmatrix} 1 & 8 \\ 27 & 64 \end{bmatrix}
   $$

代码展示了矩阵幂运算（整体矩阵相乘）和逐元素幂运算（每个元素单独运算）的区别。

## 导入所需库

In [1]:
import numpy as np
from numpy.linalg import matrix_power as pw  # 导入矩阵幂函数

## 定义矩阵

In [2]:
A = np.array([[1., 2.],  # 定义矩阵A
              [3., 4.]])

## 计算矩阵的三次幂

In [3]:
A_3 = pw(A, 3)  # 使用matrix_power计算矩阵A的三次幂
A_3

array([[ 37.,  54.],
       [ 81., 118.]])

In [4]:
A @ A @ A  # 使用矩阵乘法逐步计算A的三次幂

array([[ 37.,  54.],
       [ 81., 118.]])

## 元素逐次三次方

In [5]:
A_3_piecewise = A ** 3  # 计算矩阵A的每个元素的三次方
A_3_piecewise

array([[ 1.,  8.],
       [27., 64.]])