Chapter 04

# 矩阵加减法
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码定义了两个 $2 \times 2$ 矩阵 $A$ 和 $B$，分别为：

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 2 & 6 \\ 4 & 8 \end{bmatrix}
$$

代码随后计算了矩阵 $A$ 和 $B$ 的加法与减法。矩阵加法 $A + B$ 的结果为：

$$
A + B = \begin{bmatrix} 1+2 & 2+6 \\ 3+4 & 4+8 \end{bmatrix} = \begin{bmatrix} 3 & 8 \\ 7 & 12 \end{bmatrix}
$$

矩阵减法 $A - B$ 的结果为：

$$
A - B = \begin{bmatrix} 1-2 & 2-6 \\ 3-4 & 4-8 \end{bmatrix} = \begin{bmatrix} -1 & -4 \\ -1 & -4 \end{bmatrix}
$$

代码展示了使用 `np.add` 和 `np.subtract` 函数以及直接使用操作符完成矩阵加减法的两种实现方式。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义矩阵

In [2]:
A = np.matrix([[1, 2], 
               [3, 4]])  # 定义矩阵A
A

matrix([[1, 2],
        [3, 4]])

In [3]:
B = np.matrix([[2, 6], 
               [4, 8]])  # 定义矩阵B
B

matrix([[2, 6],
        [4, 8]])

## 矩阵加法

In [4]:
A_plus_B = np.add(A, B)  # 使用np.add函数计算矩阵A和B的和
A_plus_B

matrix([[ 3,  8],
        [ 7, 12]])

In [5]:
A_plus_B_2 = A + B  # 使用加法操作符计算矩阵A和B的和
A_plus_B_2

matrix([[ 3,  8],
        [ 7, 12]])

## 矩阵减法

In [6]:
A_minus_B = np.subtract(A, B)  # 使用np.subtract函数计算矩阵A和B的差
A_minus_B

matrix([[-1, -4],
        [-1, -4]])

In [7]:
A_minus_B_2 = A - B  # 使用减法操作符计算矩阵A和B的差
A_minus_B_2

matrix([[-1, -4],
        [-1, -4]])