Chapter 04

# NumPy数组
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

这段代码演示了如何在 NumPy 中定义不同维度的数组和矩阵，并输出每种数据结构的形状和类型。首先定义一个 $2 \times 2$ 的二维矩阵 $A_{\text{matrix}}$：

$$
A_{\text{matrix}} = \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}
$$

其类型为 `np.matrix`，形状为 $(2, 2)$。

接下来，定义了一维数组 $A_{\text{1d}} = [2, 4]$，其形状为 $(2,)$，类型为 `np.ndarray`。然后定义一个二维数组 $A_{\text{2d}}$，与 $A_{\text{matrix}}$ 具有相同的数据内容和形状 $(2, 2)$，类型为 `np.ndarray`：

$$
A_{\text{2d}} = \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}
$$

最后，通过三个 $2 \times 2$ 数组 $A1$、$A2$ 和 $A3$ 构建了一个三维数组 $A_{\text{3d}}$：

$$
A_{\text{3d}} = \begin{bmatrix} \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}, \begin{bmatrix} 1 & 3 \\ 5 & 7 \end{bmatrix}, \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} \end{bmatrix}
$$

三维数组的形状为 $(3, 2, 2)$，类型为 `np.ndarray`。这些定义展示了 NumPy 中矩阵和数组在一维、二维和三维空间的不同表示方式及其对应的形状信息。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义二维矩阵

In [2]:
A_matrix = np.matrix([[2, 4],  # 定义矩阵A_matrix
                      [6, 8]])
A_matrix

matrix([[2, 4],
        [6, 8]])

In [3]:
print(A_matrix.shape)  # 输出矩阵的形状

(2, 2)


In [4]:
print(type(A_matrix))  # 输出矩阵的类型

<class 'numpy.matrix'>


## 定义一维数组

In [5]:
A_1d = np.array([2, 4])  # 定义一维数组A_1d
A_1d

array([2, 4])

In [6]:
print(A_1d.shape)  # 输出数组的形状

(2,)


In [7]:
print(type(A_1d))  # 输出数组的类型

<class 'numpy.ndarray'>


## 定义二维数组

In [8]:
A_2d = np.array([[2, 4],  # 定义二维数组A_2d
                 [6, 8]])
A_2d

array([[2, 4],
       [6, 8]])

In [9]:
print(A_2d.shape)  # 输出数组的形状

(2, 2)


In [10]:
print(type(A_2d))  # 输出数组的类型

<class 'numpy.ndarray'>


## 定义三维数组

In [11]:
A1 = [[2, 4],  # 定义第一个二维数组A1
      [6, 8]]

In [12]:
A2 = [[1, 3],  # 定义第二个二维数组A2
      [5, 7]]

In [13]:
A3 = [[1, 0],  # 定义第三个二维数组A3
      [0, 1]]

In [14]:
A_3d = np.array([A1, A2, A3])  # 将A1、A2和A3组合为三维数组A_3d
A_3d

array([[[2, 4],
        [6, 8]],

       [[1, 3],
        [5, 7]],

       [[1, 0],
        [0, 1]]])

In [15]:
print(A_3d.shape)  # 输出三维数组的形状

(3, 2, 2)


In [16]:
print(type(A_3d))  # 输出数组的类型

<class 'numpy.ndarray'>
