Chapter 04

# diag() 函数
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)



该代码首先定义了一个 $3 \times 3$ 的矩阵 $A$：

$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}
$$

然后，代码使用 `np.diag` 提取矩阵 $A$ 的对角元素，得到向量 $a = [1, 5, 9]$。接下来，通过向量 $a$ 构建了一个新的对角矩阵 $A_{\text{diag}}$，其形式为：

$$
A_{\text{diag}} = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 5 & 0 \\ 0 & 0 & 9 \end{bmatrix}
$$

此过程展示了从一个矩阵中提取对角线元素并利用这些元素构造新的对角矩阵的操作。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义矩阵

In [2]:
A = np.matrix([[1, 2, 3],  # 定义矩阵A
               [4, 5, 6],
               [7, 8, 9]])
A 

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 提取对角元素

In [3]:
a = np.diag(A)  # 提取矩阵A的对角元素
a

array([1, 5, 9])

## 构造对角矩阵

In [4]:
A_diag = np.diag(a)  # 使用对角元素a构造对角矩阵A_diag
A_diag

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])