Chapter 04

# 矩阵乘法操作
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码演示了 NumPy 中数组和矩阵的乘法操作，分别展示了逐元素乘法和矩阵乘法的不同结果。

1. **逐元素乘法**：在第一个操作中，$A$ 和 $B$ 都是 `np.array` 类型。按逐元素方式进行乘法时，$A$ 将被广播到与 $B$ 形状相匹配，结果为：

   $$
   A \odot B = \begin{bmatrix} 1 \times 5 & 2 \times 6 \\ 1 \times 8 & 2 \times 9 \end{bmatrix} = \begin{bmatrix} 5 & 12 \\ 8 & 18 \end{bmatrix}
   $$

2. **矩阵乘法**：在第二个操作中，$A$ 为 `np.array` 类型，而 $B$ 为 `np.matrix` 类型。此时 `*` 操作符按矩阵乘法执行，计算结果为：

   $$
   A \times B = \begin{bmatrix} 1 \times 5 + 2 \times 8 & 1 \times 6 + 2 \times 9 \end{bmatrix} = \begin{bmatrix} 21 & 24 \end{bmatrix}
   $$

3. **矩阵乘法**：在第三个操作中，$A$ 和 $B$ 都是 `np.matrix` 类型，再次执行矩阵乘法，结果与第二个操作相同：

   $$
   A \times B = \begin{bmatrix} 21 & 24 \end{bmatrix}
   $$

此代码展示了在 NumPy 中 `np.array` 和 `np.matrix` 类型的不同行为及 `*` 操作符在逐元素和矩阵乘法间的区别。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义数组A和B并进行逐元素乘法

In [2]:
A = np.array([[1, 2]])  # 定义数组A

In [3]:
B = np.array([[5, 6],   # 定义数组B
              [8, 9]])

In [4]:
A * B # 打印A和B的逐元素乘法结果

array([[ 5, 12],
       [ 8, 18]])

## 定义数组A和矩阵B并进行矩阵乘法

In [5]:
A = np.array([[1, 2]])  # 定义数组A

In [6]:
B = np.matrix([[5, 6],  # 定义矩阵B
               [8, 9]])

In [7]:
A * B  # 打印A和B的矩阵乘法结果

matrix([[21, 24]])

## 定义矩阵A和矩阵B并进行矩阵乘法

In [8]:
A = np.matrix([[1, 2]])  # 定义矩阵A

In [9]:
B = np.matrix([[5, 6],   # 定义矩阵B
               [8, 9]])

In [10]:
A * B  # 打印A和B的矩阵乘法结果

matrix([[21, 24]])