Chapter 04

# 矩阵逆
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码定义了一个 $2 \times 2$ 矩阵 $A$，并计算其逆矩阵 $A^{-1}$。矩阵 $A$ 为：

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

通过求逆操作得到 $A$ 的逆矩阵：

$$
A^{-1} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

接下来，代码计算矩阵 $A$ 与其逆矩阵 $A^{-1}$ 的乘积，理论上应得到单位矩阵：

$$
A @ A^{-1} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$$

这段代码展示了如何使用 `inv` 函数计算矩阵的逆，并验证矩阵与其逆矩阵的乘积结果。

## 导入所需库

In [1]:
import numpy as np
from numpy.linalg import inv  # 导入矩阵求逆函数

## 定义矩阵A

In [2]:
A = np.array([[1., 2.],  # 定义矩阵A
              [3., 4.]])
A

array([[1., 2.],
       [3., 4.]])

## 计算矩阵的逆

In [4]:
A_inverse = inv(A)  # 计算矩阵A的逆
A_inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
A_times_A_inv = A @ A_inverse  # 计算矩阵A与其逆矩阵的乘积
A_times_A_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])