Chapter 04

# 转置
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码定义了一个 $3 \times 2$ 矩阵 $A$，并计算其转置矩阵。矩阵 $A$ 定义为：

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}
$$

矩阵的转置 $A^T$ 将行变为列，结果为一个 $2 \times 3$ 的矩阵：

$$
A^T = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix}
$$

代码使用了两种方法来计算转置矩阵：`A.transpose()` 方法和 `A.T` 属性，二者等效。这段代码展示了如何在 NumPy 中对矩阵进行转置操作。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义矩阵A

In [2]:
A = np.array([[1, 2],  # 定义矩阵A
              [3, 4],
              [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## 计算矩阵的转置

In [3]:
A_T = A.transpose()  # 使用transpose方法计算A的转置
A_T

array([[1, 3, 5],
       [2, 4, 6]])

In [4]:
A_T_2 = A.T  # 使用.T属性计算A的转置
A_T_2

array([[1, 3, 5],
       [2, 4, 6]])