Chapter 04

# 矩阵乘法
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)



该代码定义了两个 $2 \times 2$ 的矩阵 $A$ 和 $B$，并计算了它们的矩阵乘积。矩阵 $A$ 和 $B$ 分别为：

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 2 & 4 \\ 1 & 3 \end{bmatrix}
$$

矩阵乘积 $A @ B$ 的计算结果为：

$$
A @ B = \begin{bmatrix} 1 \cdot 2 + 2 \cdot 1 & 1 \cdot 4 + 2 \cdot 3 \\ 3 \cdot 2 + 4 \cdot 1 & 3 \cdot 4 + 4 \cdot 3 \end{bmatrix} = \begin{bmatrix} 4 & 10 \\ 10 & 24 \end{bmatrix}
$$

代码中，矩阵乘法操作使用了 `np.matmul` 函数和 `@` 运算符两种方式。这展示了 NumPy 中进行矩阵乘法的两种等效方法。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义两个矩阵

In [2]:
A = np.array([[1, 2],  # 定义矩阵A
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
B = np.array([[2, 4],  # 定义矩阵B
              [1, 3]])
B

array([[2, 4],
       [1, 3]])

## 矩阵乘法

In [4]:
A_times_B = np.matmul(A, B)  # 使用np.matmul计算矩阵A和B的乘积
A_times_B

array([[ 4, 10],
       [10, 24]])

In [5]:
A_times_B_2 = A @ B  # 使用@操作符计算矩阵A和B的乘积
A_times_B_2

array([[ 4, 10],
       [10, 24]])