Chapter 04

# 广播机制
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

这段代码展示了 NumPy 的广播机制，通过定义矩阵、标量、列向量和行向量进行一系列加法操作。代码首先定义了一个 $3 \times 2$ 的矩阵 $A$、一个标量 $k$、一个列向量 $c$ 和一个行向量 $r$。它们的具体定义如下：

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}, \quad k = 2, \quad c = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix}, \quad r = \begin{bmatrix} 2 & 1 \end{bmatrix}
$$

代码使用 NumPy 广播机制，分别计算以下几种加法操作：

1. **矩阵 $A$ 与标量 $k$ 相加**：标量 $k$ 会广播到矩阵 $A$ 的每个元素，即每个元素都加上 $k$ 值。这种情况下，运算结果为：

   $$
   A + k = \begin{bmatrix} 1+2 & 2+2 \\ 3+2 & 4+2 \\ 5+2 & 6+2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\ 5 & 6 \\ 7 & 8 \end{bmatrix}
   $$

2. **矩阵 $A$ 与列向量 $c$ 相加**：列向量 $c$ 被广播到矩阵 $A$ 的每一列，使得 $c$ 的每个元素与 $A$ 相同行的每个元素相加，得到：

   $$
   A + c = \begin{bmatrix} 1+3 & 2+3 \\ 3+2 & 4+2 \\ 5+1 & 6+1 \end{bmatrix} = \begin{bmatrix} 4 & 5 \\ 5 & 6 \\ 6 & 7 \end{bmatrix}
   $$

3. **矩阵 $A$ 与行向量 $r$ 相加**：行向量 $r$ 被广播到矩阵 $A$ 的每一行，使得 $r$ 的每个元素与 $A$ 相同行的每个元素相加，结果为：

   $$
   A + r = \begin{bmatrix} 1+2 & 2+1 \\ 3+2 & 4+1 \\ 5+2 & 6+1 \end{bmatrix} = \begin{bmatrix} 3 & 3 \\ 5 & 5 \\ 7 & 7 \end{bmatrix}
   $$

4. **列向量 $c$ 与行向量 $r$ 相加**：通过广播，$c$ 和 $r$ 组合成一个 $3 \times 2$ 的矩阵。每个 $c$ 的元素加到每一行的 $r$ 上，得到：

   $$
   c + r = \begin{bmatrix} 3+2 & 3+1 \\ 2+2 & 2+1 \\ 1+2 & 1+1 \end{bmatrix} = \begin{bmatrix} 5 & 4 \\ 4 & 3 \\ 3 & 2 \end{bmatrix}
   $$

该代码展示了 NumPy 广播机制的灵活性，使得矩阵、向量和标量间的加法运算在不同维度下可以直接进行。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义矩阵

In [2]:
A = np.matrix([[1, 2],  # 定义矩阵A
               [3, 4],
               [5, 6]])
A

matrix([[1, 2],
        [3, 4],
        [5, 6]])

## 定义标量

In [3]:
k = 2  # 定义标量k

## 定义列向量

In [4]:
c = np.array([[3],  # 定义列向量c
              [2],
              [1]])
c

array([[3],
       [2],
       [1]])

## 定义行向量

In [5]:
r = np.array([[2, 1]])  # 定义行向量r
r

array([[2, 1]])

## 广播原则

## 矩阵A加标量k

In [6]:
A_plus_k = A + k  # 矩阵A与标量k相加
A_plus_k

matrix([[3, 4],
        [5, 6],
        [7, 8]])

## 矩阵A加列向量c

In [7]:
A_plus_c = A + c  # 矩阵A与列向量c相加
A_plus_c

matrix([[4, 5],
        [5, 6],
        [6, 7]])

## 矩阵A加行向量r

In [8]:
A_plus_r = A + r  # 矩阵A与行向量r相加
A_plus_r

matrix([[3, 3],
        [5, 5],
        [7, 7]])

## 列向量c加行向量r

In [9]:
c_plus_r = c + r  # 列向量c与行向量r相加
c_plus_r

array([[5, 4],
       [4, 3],
       [3, 2]])