Chapter 02

# 标量乘法
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)



此代码定义了一个二维列向量 $a$，其值为：

$$
a = \begin{bmatrix} 2 \\ 2 \end{bmatrix}
$$

接下来，代码通过数乘操作生成两个新向量 $b$ 和 $c$。具体而言，$b$ 是 $a$ 的 2 倍：

$$
b = 2 \times a = 2 \times \begin{bmatrix} 2 \\ 2 \end{bmatrix} = \begin{bmatrix} 4 \\ 4 \end{bmatrix}
$$

$c$ 是 $a$ 的 $-1.5$ 倍：

$$
c = -1.5 \times a = -1.5 \times \begin{bmatrix} 2 \\ 2 \end{bmatrix} = \begin{bmatrix} -3 \\ -3 \end{bmatrix}
$$

此过程展示了向量的数乘操作，通过将标量与向量相乘来改变向量的大小和方向。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义一个列向量

In [2]:
a = np.array([[2], [2]])  # 定义向量a，值为[2, 2]
a

array([[2],
       [2]])

## 进行向量的数乘

In [3]:
b = 2 * a  # 计算b，为向量a的2倍
b

array([[4],
       [4]])

In [4]:
c = -1.5 * a  # 计算c，为向量a的-1.5倍
c

array([[-3.],
       [-3.]])