Chapter 02

# 向量夹角
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码定义了两个二维列向量 $a$ 和 $b$，并计算了它们之间夹角的余弦值、弧度和度数。

### 计算公式

向量 $a$ 和 $b$ 分别为：

$$
a = \begin{bmatrix} 4 \\ 3 \end{bmatrix}, \quad b = \begin{bmatrix} 5 \\ -2 \end{bmatrix}
$$

余弦夹角公式为：

$$
\cos \theta = \frac{a \cdot b}{\|a\|_2 \|b\|_2} = \frac{a^T b}{\|a\|_2 \|b\|_2}
$$

接着，使用反余弦函数计算角度的弧度值：

$$
\theta = \arccos(\cos \theta)
$$

最后将弧度值转换为角度：

$$
\theta_{\text{degree}} = \theta \times \frac{180}{\pi}
$$

代码中的运算展示了向量间夹角的计算方法，包括余弦、弧度和度数转换。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义两个列向量

In [2]:
a, b = np.array([[4], [3]]), np.array([[5], [-2]])  # 定义向量a和b

## 计算余弦值

In [3]:
cos_theta = (a.T @ b) / (np.linalg.norm(a, 2) * np.linalg.norm(b, 2))  
# 计算向量a和b之间夹角的余弦值
cos_theta

array([[0.51994695]])

## 计算夹角的弧度值

In [4]:
cos_radian = np.arccos(cos_theta)  # 计算余弦值对应的弧度
cos_radian

array([[1.02400749]])

## 将弧度转换为度数

In [5]:
cos_degree = cos_radian * (180 / np.pi)  # 将弧度转换为度数
cos_degree

array([[58.67130713]])