Chapter 02

# 向量加减法
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

这段代码定义了两个二维列向量 $a$ 和 $b$，并计算了它们的加法与减法。具体来说，向量 $a$ 定义为：

$$
a = \begin{bmatrix} -2 \\ 5 \end{bmatrix}
$$

向量 $b$ 定义为：

$$
b = \begin{bmatrix} 5 \\ -1 \end{bmatrix}
$$

代码首先计算了 $a$ 和 $b$ 的向量加法，得到结果向量 $a + b$，其计算过程为：

$$
a + b = \begin{bmatrix} -2 \\ 5 \end{bmatrix} + \begin{bmatrix} 5 \\ -1 \end{bmatrix} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}
$$

此外，代码还展示了向量减法 $a - b$ 和 $b - a$，分别为：

$$
a - b = \begin{bmatrix} -2 \\ 5 \end{bmatrix} - \begin{bmatrix} 5 \\ -1 \end{bmatrix} = \begin{bmatrix} -7 \\ 6 \end{bmatrix}
$$

$$
b - a = \begin{bmatrix} 5 \\ -1 \end{bmatrix} - \begin{bmatrix} -2 \\ 5 \end{bmatrix} = \begin{bmatrix} 7 \\ -6 \end{bmatrix}
$$

代码中分别使用了直接运算（如 `a + b`）和 `NumPy` 函数 `np.add` 与 `np.subtract` 来完成加法和减法操作。这种处理方式展示了向量的基本线性代数操作。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义两个列向量

In [2]:
a = np.array([[-2], [5]])  # 定义向量a，值为[-2, 5]
a

array([[-2],
       [ 5]])

In [3]:
b = np.array([[5], [-1]])  # 定义向量b，值为[5, -1]
b

array([[ 5],
       [-1]])

## 计算向量加法

In [4]:
a_plus_b = a + b  # 使用直接加法计算a和b的和
a_plus_b

array([[3],
       [4]])

In [5]:
a_plus_b_2 = np.add(a, b)  # 使用np.add函数计算a和b的和
a_plus_b_2

array([[3],
       [4]])

## 计算向量减法

In [6]:
a_minus_b = a - b  # 计算a减去b的差
a_minus_b

array([[-7],
       [ 6]])

In [7]:
a_minus_b_2 = np.subtract(a, b)  # 使用np.subtract函数计算a减去b的差
a_minus_b_2

array([[-7],
       [ 6]])

In [8]:
b_minus_a = b - a  # 计算b减去a的差
b_minus_a

array([[ 7],
       [-6]])

In [9]:
b_minus_a_2 = np.subtract(b, a)  # 使用np.subtract函数计算b减去a的差
b_minus_a_2

array([[ 7],
       [-6]])