Chapter 02

# 逐项积
Book_4《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习 (第二版)


此代码定义了两个三维向量 $a$ 和 $b$，并计算了它们的逐元素积（即对应元素相乘）。代码中既使用了行向量形式也使用了列向量形式的 $a$ 和 $b$ 来演示逐元素乘法的计算。

### 逐元素乘法公式
对于两个向量 $a = \begin{bmatrix} a_1 \\ a_2 \\ a_3 \end{bmatrix}$ 和 $b = \begin{bmatrix} b_1 \\ b_2 \\ b_3 \end{bmatrix}$，逐元素积定义为：

$$
a \odot b = \begin{bmatrix} a_1 \cdot b_1 \\ a_2 \cdot b_2 \\ a_3 \cdot b_3 \end{bmatrix}
$$

代码中的计算展示了逐元素乘法的两种实现方式：使用 `np.multiply` 函数和直接使用 `*` 操作符。结果得到一个新向量，其中每个元素为对应元素相乘的值。

## 导入所需库

In [1]:
import numpy as np  # 导入NumPy库，用于数值计算

## 定义两个行向量

In [2]:
a = np.array([-2, 1, 1])  # 定义向量a

In [3]:
b = np.array([1, -2, -1])  # 定义向量b

## 计算行向量的逐元素积

In [4]:
a_times_b = np.multiply(a, b)  # 计算a和b的逐元素积
a_times_b

array([-2, -2, -1])

In [5]:
a_times_b_2 = a * b  # 使用*操作符计算a和b的逐元素积
a_times_b_2

array([-2, -2, -1])

## 定义两个列向量

In [6]:
a_col = np.array([[-2], [1], [1]])  # 定义列向量a_col

In [7]:
b_col = np.array([[1], [-2], [-1]])  # 定义列向量b_col

## 计算列向量的逐元素积

In [8]:
a_times_b_col = np.multiply(a_col, b_col)  # 计算a_col和b_col的逐元素积
a_times_b_col

array([[-2],
       [-2],
       [-1]])

In [9]:
a_times_b_col_2 = a_col * b_col  # 使用*操作符计算a_col和b_col的逐元素积
a_times_b_col_2

array([[-2],
       [-2],
       [-1]])